# Generated by Django 5.0.6 on 2024-07-01 07:04

import django.db.models.deletion
import spai_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0002_alter_user_slug_value_alter_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to=spai_app.models.user_detail_image_path)),
                ('specialized_in', models.CharField(blank=True, max_length=50, null=True)),
                ('research_interest', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
