# Generated by Django 5.0.6 on 2024-12-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0002_internshipapplication_internship_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='executive',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SECRETARY'), (2, 'PRESIDENT')], null=True),
        ),
    ]
