# Generated by Django 5.0.6 on 2024-12-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0003_alter_user_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_key',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
