# Generated by Django 5.0.6 on 2024-07-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0004_alter_userdetailmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='SPAI/images/user_details'),
        ),
    ]
