# Generated by Django 5.0.6 on 2024-12-23 05:19

import django.db.models.deletion
import spai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0005_lifemembers_lm_key_lifemembers_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to=spai_app.models.event_document_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_doc', to='spai_app.eventmanagement')),
            ],
        ),
    ]
