# Generated by Django 5.0.6 on 2024-07-01 14:57

import spai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0005_alter_userdetailmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=spai_app.models.user_detail_image_path),
        ),
    ]
