# Generated by Django 5.0.2 on 2024-07-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0006_alter_userdetailmodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='SPAI/images/Events')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_link', models.TextField(blank=True, null=True)),
                ('time', models.TimeField()),
            ],
        ),
    ]
