# Generated by Django 5.1.4 on 2024-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0007_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
