# Generated by Django 5.0.2 on 2024-07-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0007_eventmanagement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmanagement',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='eventmanagement',
            name='time',
        ),
    ]
