# Generated by Django 5.1.4 on 2024-12-27 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0008_alter_passwordresetrequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnnualSubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_sub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
