# Generated by Django 5.0.2 on 2024-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0008_rename_date_eventmanagement_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmanagement',
            name='registration_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
