# Generated by Django 5.0.2 on 2024-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0009_alter_eventmanagement_registration_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmanagement',
            name='registration_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
