# Generated by Django 5.1.4 on 2024-12-27 19:59

import django.db.models.deletion
import spai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0009_user_annual_subscription_annualsubscriptionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=spai_app.models.subscription_payment_path)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_model_subscription', to='spai_app.annualsubscriptionmodel')),
            ],
        ),
    ]
