# Generated by Django 5.1.4 on 2024-12-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0010_subscriptionpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
