# Generated by Django 5.0.2 on 2024-08-24 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0010_alter_eventmanagement_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymanagement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spai_app.eventmanagement'),
        ),
        migrations.AddField(
            model_name='gallerymanagement',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gallerymanagement',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spai_app.gallerymanagement')),
            ],
        ),
    ]
