# Generated by Django 5.0.2 on 2024-08-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0011_gallerymanagement_event_gallerymanagement_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='images',
        ),
    ]
