# Generated by Django 5.0.6 on 2024-08-25 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0012_rename_image_galleryimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymanagement',
            name='image',
            field=models.ImageField(null=True, upload_to='SPAI/images/gallery'),
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reported_date', models.DateField(auto_now_add=True)),
                ('payment_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'QR CODE'), (2, 'BANK TRANSFER')], null=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
