# Generated by Django 5.1.4 on 2024-12-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0012_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
