# Generated by Django 5.0.6 on 2024-08-25 11:52

import spai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0013_alter_gallerymanagement_image_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=spai_app.models.user_detail_payment_path),
        ),
    ]
