# Generated by Django 5.1.4 on 2024-12-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0013_subscriptionpayment_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
