# Generated by Django 5.0.6 on 2024-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0014_paymentmodel_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('membership_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('is_expire', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
