# Generated by Django 5.0.6 on 2024-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0016_rename_is_expire_lifemembers_active_lifemembers_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('interest_area', models.CharField(max_length=100)),
                ('location_preference', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('passing_year', models.PositiveIntegerField()),
                ('score', models.CharField(max_length=10)),
                ('apply_date', models.DateField(auto_now=True)),
                ('apply_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
