# Generated by Django 5.1.4 on 2025-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0017_subscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('publish', models.BooleanField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
