# Generated by Django 5.0.6 on 2024-11-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0017_internshipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifemembers',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
