# Generated by Django 5.0.6 on 2024-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0018_alter_lifemembers_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanagement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
