# Generated by Django 5.1.4 on 2025-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0019_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
