# Generated by Django 5.0.6 on 2024-12-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0019_eventmanagement_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
