# Generated by Django 4.2.18 on 2025-01-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0020_journalquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymanagement',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
