# Generated by Django 5.0.6 on 2024-12-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0020_user_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
