# Generated by Django 5.1.4 on 2025-01-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0020_journalquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='research_interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetailmodel',
            name='specialized_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
