# Generated by Django 5.1.4 on 2025-01-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0021_alter_userdetailmodel_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymanagement',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
