# Generated by Django 5.0.6 on 2024-12-11 19:39

import django.db.models.deletion
import spai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0021_user_date_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('research_area', models.CharField(max_length=255)),
                ('paper_file', models.FileField(upload_to=spai_app.models.paper_submission_path)),
                ('editor_message', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('paper_no', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='spai_app.manuscript')),
            ],
        ),
    ]
