# Generated by Django 5.1.4 on 2025-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0022_alter_gallerymanagement_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='executive',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SECRETARY'), (2, 'PRESIDENT'), (3, 'EXECUTIVE')], null=True),
        ),
    ]
