# Generated by Django 5.1.4 on 2025-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0024_alter_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='president_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secretary_approval',
            field=models.BooleanField(default=False),
        ),
    ]
