# Generated by Django 5.1.4 on 2025-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0025_user_president_approval_user_secretary_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
