# Generated by Django 5.1.4 on 2025-04-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spai_app', '0026_user_original_date_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_banner_display', to='spai_app.eventmanagement')),
            ],
        ),
    ]
